# Projeto de Regressão Linear Múltipla 

**O Objetivo:** Prever o preço final de venda das casas com base nas suas características.

**O que é:** Um conjunto de dados histórico sobre vendas de imóveis residenciais ocorridas na cidade de Ames, Iowa (EUA) entre 2006 e 2010.

## 1) Fonte dos dados 

In [1]:
import pandas as pd 
from sklearn.datasets import fetch_openml

# Carrega o dataset de Ames Housing (ID 42165 no OpenML)
ames = fetch_openml(data_id=42165, as_frame=True, parser="auto")

# Separa as features (X) e o alvo (y)
df = ames.data
df['SalePrice'] = ames.target

df.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000


## 2) Análise Exploratória 

### 2.1) Dicionário de Dados - Ames Housing Dataset

### Identificação, Venda e Variável Alvo

| Nome | Tradução | Descrição |
|---|---|---|
| **SalePrice** | Preço de Venda | Preço final de venda da propriedade em dólares *(Variável Alvo / Target)*. |
| **MoSold** | Mês de Venda | Mês em que a propriedade foi vendida (1 a 12). |
| **YrSold** | Ano de Venda | Ano em que a propriedade foi vendida. |
| **SaleType** | Tipo de Venda | Tipo de documento/opção de financiamento da transação (ex: à vista, convênio bancário). |
| **SaleCondition** | Condição de Venda | Condições sob as quais a casa foi vendida (ex: venda normal, execução hipotecária, entre familiares). |

### Localização e Terreno

| Nome | Tradução | Descrição |
|---|---|---|
| **MSSubClass** | Subclasse da Propriedade | Identifica o tipo de imóvel construído envolvido na venda (ex: 1 andar moderno, 2 andares antigo). |
| **MSZoning** | Zoneamento | Classificação geral do zoneamento urbano do lote (ex: Residencial Alta/Baixa Densidade, Comercial). |
| **LotFrontage** | Testada do Lote | Extensão da frente do terreno conectada à rua (medida em pés). |
| **LotArea** | Área do Lote | Área total do terreno (em pés quadrados). |
| **Street** | Tipo de Acesso Viário | Tipo de pavimentação da rua de acesso ao imóvel (cascalho ou asfalto/pavimentado). |
| **Alley** | Beco / Servidão | Tipo de acesso secundário por beco à propriedade (cascalho, pavimentado ou sem beco). |
| **LotShape** | Formato do Lote | Formato do terreno (regular ou níveis de irregularidade). |
| **LandContour** | Nivelamento do Terreno | Topografia do terreno (plano, em aclive, em declive, etc.). |
| **Utilities** | Serviços Utilitários | Tipos de serviços públicos disponíveis no lote (água, luz, gás, esgoto). |
| **LotConfig** | Configuração do Lote | Posição e tipo do lote dentro da quadra (ex: esquina, meio de quadra, lote interno). |
| **LandSlope** | Inclinação do Terreno | Grau de inclinação da terra (suave, moderada ou íngreme). |
| **Neighborhood** | Bairro | Localidade ou bairro físico dentro dos limites do município de Ames, Iowa. |
| **Condition1** | Condição de Proximidade 1 | Proximidade a infraestruturas urbanas (vias expressas, ferrovias, parques). |
| **Condition2** | Condição de Proximidade 2 | Segunda condição de proximidade (caso exista mais de uma presente). |

### Estrutura e Qualidade Geral da Construção

| Nome | Tradução | Descrição |
|---|---|---|
| **BldgType** | Tipo de Edificação | Estilo de habitação (ex: unifamiliar isolada, duplex, geminada). |
| **HouseStyle** | Estilo Arquitetônico | Estilo da moradia (ex: 1 andar, 2 andares, meio nível / *split level*). |
| **OverallQual** | Qualidade Geral | Avaliação geral do material de construção e acabamento do imóvel (nota de 1 a 10). |
| **OverallCond** | Condição Geral | Avaliação do estado geral de conservação atual do imóvel (nota de 1 a 10). |
| **YearBuilt** | Ano de Construção | Ano em que a casa foi construída originalmente. |
| **YearRemodAdd** | Ano de Reforma | Ano da última reforma ou ampliação (igual ao ano de construção se nunca reformada). |
| **RoofStyle** | Estilo do Telhado | Formato e tipo arquitetônico do telhado (ex: duas águas, quatro águas, plano). |
| **RoofMatl** | Material do Telhado | Material utilizado na cobertura do telhado (telha cerâmica, composição, etc.). |
| **Exterior1st** | Revestimento Externo 1 | Revestimento principal das paredes externas do imóvel. |
| **Exterior2nd** | Revestimento Externo 2 | Revestimento secundário das paredes externas (se houver mais de um). |
| **MasVnrType** | Tipo de Alvenaria Decorativa | Tipo de revestimento de pedra ou tijolo na fachada externa. |
| **MasVnrArea** | Área de Alvenaria Decorativa | Área coberta por alvenaria decorativa externa (em pés quadrados). |
| **ExterQual** | Qualidade do Exterior | Avaliação da qualidade dos materiais do exterior do imóvel. |
| **ExterCond** | Condição do Exterior | Avaliação do estado atual de conservação do exterior. |
| **Foundation** | Tipo de Fundação | Tipo de alicerce da edificação (concreto, bloco de cimento, tijolo, etc.). |

### Porão (Basement)

| Nome | Tradução | Descrição |
|---|---|---|
| **BsmtQual** | Qualidade do Porão | Avaliação da altura útil e qualidade do porão. |
| **BsmtCond** | Condição do Porão | Avaliação do estado geral de preservação do porão. |
| **BsmtExposure** | Exposição do Porão | Nível de saída direta ou presença de janelas em nível de solo para o porão. |
| **BsmtFinType1** | Tipo de Acabamento 1 do Porão | Classificação do acabamento da área construída principal do porão. |
| **BsmtFinSF1** | Área Acabada 1 do Porão | Área da seção principal acabada do porão (em pés quadrados). |
| **BsmtFinType2** | Tipo de Acabamento 2 do Porão | Classificação da segunda área acabada do porão (caso exista). |
| **BsmtFinSF2** | Área Acabada 2 do Porão | Área da segunda seção acabada do porão (em pés quadrados). |
| **BsmtUnfSF** | Área Inacabada do Porão | Área bruta sem acabamento no porão (em pés quadrados). |
| **TotalBsmtSF** | Área Total do Porão | Soma da área total do porão em pés quadrados (acabada + inacabada). |

### Instalações e Sistemas Internos

| Nome | Tradução | Descrição |
|---|---|---|
| **Heating** | Tipo de Aquecimento | Tipo de sistema de aquecimento da casa (ex: ar forçado, radiador). |
| **HeatingQC** | Qualidade do Aquecimento | Avaliação da qualidade e eficiência do sistema de aquecimento. |
| **CentralAir** | Ar Condicionado Central | Indica a presença de sistema de ar condicionado central (`Y` = Sim, `N` = Não). |
| **Electrical** | Sistema Elétrico | Tipo e qualidade do painel e da fiação elétrica. |

### Áreas Habitáveis e Cômodos (Superfície Acima do Solo)

| Nome | Tradução | Descrição |
|---|---|---|
| **1stFlrSF** | Área do 1º Andar | Área em pés quadrados do primeiro andar. |
| **2ndFlrSF** | Área do 2º Andar | Área em pés quadrados do segundo andar. |
| **LowQualFinSF** | Área com Acabamento Baixo | Área em pés quadrados com acabamento de baixa qualidade nos andares superiores. |
| **GrLivArea** | Área Habituável Acima do Solo | Área total de espaço habitável situado acima do nível do solo (em pés quadrados). |
| **BsmtFullBath** | Banheiros Completos no Porão | Quantidade de banheiros completos localizados no porão. |
| **BsmtHalfBath** | Lavabos no Porão | Quantidade de lavabos (sem chuveiro/banheira) localizados no porão. |
| **FullBath** | Banheiros Completos (Térreo/Sup.) | Quantidade de banheiros completos localizados acima do porão. |
| **HalfBath** | Lavabos (Térreo/Sup.) | Quantidade de lavabos localizados acima do porão. |
| **BedroomAbvGr** | Quartos | Número de quartos situados acima do nível do porão. |
| **KitchenAbvGr** | Cozinhas | Número de cozinhas situadas acima do nível do porão. |
| **KitchenQual** | Qualidade da Cozinha | Avaliação da qualidade e conservação da cozinha. |
| **TotRmsAbvGrd** | Total de Cômodos | Número total de cômodos acima do solo (não inclui banheiros). |
| **Functional** | Funcionalidade da Casa | Avaliação da funcionalidade geral do imóvel (deduções por danos estruturais/defeitos). |
| **Fireplaces** | Lareiras | Quantidade de lareiras na casa. |
| **FireplaceQu** | Qualidade da Lareira | Avaliação da qualidade das lareiras. |

### Garagem

| Nome | Tradução | Descrição |
|---|---|---|
| **GarageType** | Tipo de Garagem | Localização e tipo de garagem (anexa à casa, destacada, embutida, etc.). |
| **GarageYrBlt** | Ano de Construção da Garagem | Ano em que a garagem foi construída. |
| **GarageFinish** | Acabamento Interno da Garagem | Nível de acabamento interior da garagem (completamente acabada, inacabada, etc.). |
| **GarageCars** | Capacidade de Veículos | Capacidade da garagem medida em número de carros. |
| **GarageArea** | Área da Garagem | Tamanho total da garagem (em pés quadrados). |
| **GarageQual** | Qualidade da Garagem | Avaliação da qualidade da construção da garagem. |
| **GarageCond** | Condição da Garagem | Avaliação do estado atual de conservação da garagem. |
| **PavedDrive** | Pavimentação da Garagem | Condição do piso do acesso de entrada da garagem (pavimentado, parcial, terra/cascalho). |

### Lazer e Áreas Externas

| Nome | Tradução | Descrição |
|---|---|---|
| **WoodDeckSF** | Área de Deck de Madeira | Área do deck externo de madeira (em pés quadrados). |
| **OpenPorchSF** | Área de Varanda Aberta | Área da varanda coberta sem fechamento lateral (em pés quadrados). |
| **EnclosedPorch** | Área de Varanda Fechada | Área da varanda fechada (em pés quadrados). |
| **3SsnPorch** | Varanda 3 Estações | Área de varanda adaptada para uso em três estações do ano (em pés quadrados). |
| **ScreenPorch** | Varanda com Tela | Área de varanda fechada com tela de proteção (em pés quadrados). |
| **PoolArea** | Área da Piscina | Área coberta pela piscina em pés quadrados. |
| **PoolQC** | Qualidade da Piscina | Avaliação da qualidade e das instalações da piscina. |
| **Fence** | Cerca | Tipo e nível de privacidade/qualidade da cerca da propriedade. |
| **MiscFeature** | Recurso Adicional | Recursos extras não listados em outras colunas (ex: galpão, elevador, quadra de tênis). |
| **MiscVal** | Valor do Recurso Adicional | Valor monetário estimado atribuído aos recursos adicionais (em dólares). |

### 2.2) Verificando valores ausentes 

In [2]:
# Verificando valores ausentes 

pd.DataFrame(round(df.isna().sum()[df.isna().sum() > 0]*100/df.shape[0], 1), columns=['Ausentes (%)'])

,Ausentes (%)
LotFrontage,17.7
Alley,93.8
MasVnrType,0.5
MasVnrArea,0.5
BsmtQual,2.5
BsmtCond,2.5
BsmtExposure,2.6
BsmtFinType1,2.5
BsmtFinType2,2.6
Electrical,0.1


In [3]:
# As variáveis Alley, FireplaceQu, PoolQC, Fence e MiscFeature serão eliminadas pois possuem valores ausentes em mais de 20% do seu total. 
# As demais terão os valores ausentes imputados. 

df = df.drop(['Alley', 'FireplaceQu', 'PoolQC', 'Fence', 'MiscFeature'], axis=1)

### 2.3) Verificando os tipos das variáveis 

In [4]:
# Existem variável categóricas ordinais, ou seja, quando ela for codificada deve manter a ordem de importância das categorias
# Por exemplo:
df['GarageQual'].unique()

<StringArray>
['TA', 'Fa', 'Gd', nan, 'Ex', 'Po']
Length: 6, dtype: str

| Sigla | Termo em Inglês | Tradução / Significado |
| :--- | :--- | :--- |
| **Po** | Poor | Péssimo / Fraco |
| **Fa** | Fair | Razoável / Aceitável |
| **TA** | Typical / Average | Típico / Média padrão |
| **Gd** | Good | Bom |
| **Ex** | Excellent | Excelente |
| **nan** | Missing Value | Ausente (indica que a casa NÃO possui aquele item) |

In [5]:
# O nan nessas colunas não é um valor ausente (erro) ele simplemente indica que não há como avaliar o item. Por exemplo GarageQual = nan significa que a casa não possui garagem. 
# Após inspeção do dataframe, detectamos as seguintes colunas nessa condição. 

# Lista de colunas que usam essa escala
colunas_qualidade = ['ExterQual', 'ExterCond', 'BsmtQual', 'BsmtCond', 'HeatingQC', 'KitchenQual', 'GarageQual', 'GarageCond']

# Dicionário de mapeamento
mapeamento = {'Po': 1, 'Fa': 2, 'TA': 3, 'Gd': 4, 'Ex': 5}

for col in colunas_qualidade:
    df[col] = df[col].map(mapeamento).fillna(0).astype(int)

In [6]:
# 1. BsmtExposure: Exposição do porão (sem porão = 0)
map_bsmt_exposure = {
    'No': 1,  # Sem exposição
    'Mn': 2,  # Exposição mínima
    'Av': 3,  # Exposição média
    'Gd': 4   # Boa exposição
}
df['BsmtExposure'] = df['BsmtExposure'].map(map_bsmt_exposure).fillna(0).astype(int)

# 2. BsmtFinType1 e BsmtFinType2: Qualidade do acabamento do porão (sem porão = 0)
map_bsmt_fin = {
    'Unf': 1,  # Unfinished (Não acabado)
    'LwQ': 2,  # Low Quality
    'Rec': 3,  # Average Rec Room
    'BLQ': 4,  # Below Average Living Area
    'ALQ': 5,  # Average Living Area
    'GLQ': 6   # Good Living Area
}

df['BsmtFinType1'] = df['BsmtFinType1'].map(map_bsmt_fin).fillna(0).astype(int)
df['BsmtFinType2'] = df['BsmtFinType2'].map(map_bsmt_fin).fillna(0).astype(int)

# 3. Functional: Funcionalidade da casa (Supõe-se 'Typ' como padrão se faltar)
map_functional = {
    'Sal': 1,   # Salvage only
    'Sev': 2,   # Severely Damaged
    'Maj2': 3,  # Major Deductions 2
    'Maj1': 4,  # Major Deductions 1
    'Mod': 5,   # Moderate Deductions
    'Min2': 6,  # Minor Deductions 2
    'Min1': 7,  # Minor Deductions 1
    'Typ': 8    # Typical Functionality
}

df['Functional'] = df['Functional'].map(map_functional).fillna(0).astype(int)

# 4. GarageFinish: Acabamento do interior da garagem (sem garagem = 0)
map_garage_finish = {
    'Unf': 1,  # Unfinished
    'RFn': 2,  # Rough Finished
    'Fin': 3   # Finished
}

df['GarageFinish'] = df['GarageFinish'].map(map_garage_finish).fillna(0).astype(int)

# 5. Utilities: Utilidades disponíveis na casa
map_utilities = {
    'ELO': 1,     # Electricity only
    'NoSeWa': 2,  # Electricity and Gas Only
    'NoSewr': 3,  # Electricity, Gas, and Water
    'AllPub': 4   # All public Utilities (E,G,W,& S)
}

df['Utilities'] = df['Utilities'].map(map_utilities).fillna(0).astype(int)

In [7]:
# Analisando as variáveis categoricas nominais 

df_str = df.select_dtypes(include=['object', 'string'])

df_str.head()

,MSZoning,Street,LotShape,LandContour,LotConfig,LandSlope,Neighborhood,Condition1,Condition2,BldgType,...,Exterior2nd,MasVnrType,Foundation,Heating,CentralAir,Electrical,GarageType,PavedDrive,SaleType,SaleCondition
0,RL,Pave,Reg,Lvl,Inside,Gtl,CollgCr,Norm,Norm,1Fam,...,VinylSd,BrkFace,PConc,GasA,Y,SBrkr,Attchd,Y,WD,Normal
1,RL,Pave,Reg,Lvl,FR2,Gtl,Veenker,Feedr,Norm,1Fam,...,MetalSd,None,CBlock,GasA,Y,SBrkr,Attchd,Y,WD,Normal
2,RL,Pave,IR1,Lvl,Inside,Gtl,CollgCr,Norm,Norm,1Fam,...,VinylSd,BrkFace,PConc,GasA,Y,SBrkr,Attchd,Y,WD,Normal
3,RL,Pave,IR1,Lvl,Corner,Gtl,Crawfor,Norm,Norm,1Fam,...,'Wd Shng',None,BrkTil,GasA,Y,SBrkr,Detchd,Y,WD,Abnorml
4,RL,Pave,IR1,Lvl,FR2,Gtl,NoRidge,Norm,Norm,1Fam,...,VinylSd,BrkFace,PConc,GasA,Y,SBrkr,Attchd,Y,WD,Normal


In [8]:
# Verificando quantas categorias cada uma delas possui.
# Acima de 15 categorias temos uma cardinalidade alta, o que pode prejudicar o aprendizado do algoritmo e causar uma explosão na dimensionalidade do dataframe. 

contagem_categorias = df_str.nunique()

print(contagem_categorias[contagem_categorias>15])

Neighborhood    25
Exterior2nd     16
dtype: int64


In [9]:
# Para corrigir isso, vamos agrupar categorias com baixa representatividade e chamá-las de 'Others' 

contagem_categorias = df_str.nunique()

# Filtra colunas que têm mais de 15 categorias únicas
for var in contagem_categorias[contagem_categorias > 15].index:
    # Pega o nome das 14 categorias com MAIOR frequência
    top_14_categorias = df[var].value_counts().nlargest(14).index
    # Tudo o que NÃO estiver nesse Top 14 vira 'Others'
    df[var] = df[var].where(df[var].isin(top_14_categorias), 'Others')

In [10]:
df['Neighborhood'].value_counts()

Neighborhood
Others     225
NAmes      225
CollgCr    150
OldTown    113
Edwards    100
Somerst     86
Gilbert     79
NridgHt     77
Sawyer      74
NWAmes      73
SawyerW     59
BrkSide     58
Crawfor     51
Mitchel     49
NoRidge     41
Name: count, dtype: int64

In [10]:
# Verificando os tipos de dados disponíveis 

df.dtypes.value_counts()

int64      49
str        24
float64     3
Name: count, dtype: int64

In [11]:
# Analisando as variáveis numéricas  

df_num = df.select_dtypes(include=['int64', 'float64'])

df_num.head()

,Id,MSSubClass,LotFrontage,LotArea,Utilities,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,...,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SalePrice
0,1,60,65.0,8450,4,7,5,2003,2003,196.0,...,0,61,0,0,0,0,0,2,2008,208500
1,2,20,80.0,9600,4,6,8,1976,1976,0.0,...,298,0,0,0,0,0,0,5,2007,181500
2,3,60,68.0,11250,4,7,5,2001,2002,162.0,...,0,42,0,0,0,0,0,9,2008,223500
3,4,70,60.0,9550,4,7,5,1915,1970,0.0,...,0,35,272,0,0,0,0,2,2006,140000
4,5,60,84.0,14260,4,8,5,2000,2000,350.0,...,192,84,0,0,0,0,0,12,2008,250000


In [12]:
# Temos que eliminar as variável categoricas do tipo int nessa análise.
# O limite adotado acima deve ser o mesmo aqui. 

contagem_continuas = df_num.nunique()

print(contagem_continuas[contagem_continuas>15])

Id               1460
LotFrontage       110
LotArea          1073
YearBuilt         112
YearRemodAdd       61
MasVnrArea        327
BsmtFinSF1        637
BsmtFinSF2        144
BsmtUnfSF         780
TotalBsmtSF       721
1stFlrSF          753
2ndFlrSF          417
LowQualFinSF       24
GrLivArea         861
GarageYrBlt        97
GarageArea        441
WoodDeckSF        274
OpenPorchSF       202
EnclosedPorch     120
3SsnPorch          20
ScreenPorch        76
MiscVal            21
SalePrice         663
dtype: int64


### 2.4) Fazendo engenharia de variáveis 

In [13]:
# Temos variáveis temporais no conjunto de dados 
# Podemos fazer as seguintes tranformações para melhorar o aprendizado do algoritmo 

# Idade da casa no momento da venda (Depreciação principal)
df['HouseAge'] = df['YrSold'] - df['YearBuilt']

# Anos desde a última reforma no momento da venda (Valorização por modernização)
df['RemodAge'] = df['YrSold'] - df['YearRemodAdd']

# Criando uma variável que indica se a casa já foi reformada 
df['IsRemodeled'] = (df['YearBuilt'] != df['YearRemodAdd']).astype(int)

# Criando uma variável que indica se a casa foi vendida no ano em que foi construída
df['IsNewHouse'] = (df['YrSold'] == df['YearBuilt']).astype(int) 

# Criando estações do ano (EUA: Primavera/Verão aquecidos)
def get_season(month):
    if month in [3, 4, 5]: return 'Spring'
    elif month in [6, 7, 8]: return 'Summer'
    elif month in [9, 10, 11]: return 'Autumn'
    else: return 'Winter'

df['SeasonSold'] = df['MoSold'].apply(get_season)

# Eliminando as variáveis utilizadas 

df = df.drop(columns=['YrSold', 'YearBuilt', 'YearRemodAdd', 'YearBuilt', 'MoSold' ])

In [14]:
df.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,LotShape,LandContour,Utilities,LotConfig,...,PoolArea,MiscVal,SaleType,SaleCondition,SalePrice,HouseAge,RemodAge,IsRemodeled,IsNewHouse,SeasonSold
0,1,60,RL,65.0,8450,Pave,Reg,Lvl,4,Inside,...,0,0,WD,Normal,208500,5,5,0,0,Winter
1,2,20,RL,80.0,9600,Pave,Reg,Lvl,4,FR2,...,0,0,WD,Normal,181500,31,31,0,0,Spring
2,3,60,RL,68.0,11250,Pave,IR1,Lvl,4,Inside,...,0,0,WD,Normal,223500,7,6,1,0,Autumn
3,4,70,RL,60.0,9550,Pave,IR1,Lvl,4,Corner,...,0,0,WD,Abnorml,140000,91,36,1,0,Winter
4,5,60,RL,84.0,14260,Pave,IR1,Lvl,4,FR2,...,0,0,WD,Normal,250000,8,8,0,0,Winter


In [15]:
# Selecionando o tipos numéricos 

df_num = df.select_dtypes(include=['int64', 'float64'])
df_num.head()

,Id,MSSubClass,LotFrontage,LotArea,Utilities,OverallQual,OverallCond,MasVnrArea,ExterQual,ExterCond,...,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,SalePrice,HouseAge,RemodAge,IsRemodeled,IsNewHouse
0,1,60,65.0,8450,4,7,5,196.0,4,3,...,0,0,0,0,0,208500,5,5,0,0
1,2,20,80.0,9600,4,6,8,0.0,3,3,...,0,0,0,0,0,181500,31,31,0,0
2,3,60,68.0,11250,4,7,5,162.0,4,3,...,0,0,0,0,0,223500,7,6,1,0
3,4,70,60.0,9550,4,7,5,0.0,3,3,...,272,0,0,0,0,140000,91,36,1,0
4,5,60,84.0,14260,4,8,5,350.0,4,3,...,0,0,0,0,0,250000,8,8,0,0


In [16]:
LIMITE = 15
contagem_continuas = df_num.nunique()
print(contagem_continuas[contagem_continuas>LIMITE])

Id               1460
LotFrontage       110
LotArea          1073
MasVnrArea        327
BsmtFinSF1        637
BsmtFinSF2        144
BsmtUnfSF         780
TotalBsmtSF       721
1stFlrSF          753
2ndFlrSF          417
LowQualFinSF       24
GrLivArea         861
GarageYrBlt        97
GarageArea        441
WoodDeckSF        274
OpenPorchSF       202
EnclosedPorch     120
3SsnPorch          20
ScreenPorch        76
MiscVal            21
SalePrice         663
HouseAge          122
RemodAge           62
dtype: int64


In [17]:
df_cont = df[contagem_continuas[contagem_continuas>15].index]
df_cont.head()

,Id,LotFrontage,LotArea,MasVnrArea,BsmtFinSF1,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,1stFlrSF,2ndFlrSF,...,GarageArea,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,MiscVal,SalePrice,HouseAge,RemodAge
0,1,65.0,8450,196.0,706,0,150,856,856,854,...,548,0,61,0,0,0,0,208500,5,5
1,2,80.0,9600,0.0,978,0,284,1262,1262,0,...,460,298,0,0,0,0,0,181500,31,31
2,3,68.0,11250,162.0,486,0,434,920,920,866,...,608,0,42,0,0,0,0,223500,7,6
3,4,60.0,9550,0.0,216,0,540,756,961,756,...,642,0,35,272,0,0,0,140000,91,36
4,5,84.0,14260,350.0,655,0,490,1145,1145,1053,...,836,192,84,0,0,0,0,250000,8,8


### 2.5) Verificando a distribuição das variáveis 

In [18]:
# Verificando a assimetria 
# Lembrando que uma distribuição normal possui assimetria = 0 ( perfeitamente simétrica)
# Entre -0.5 e 0.5 temos uma distribuição aproximadamente simétrica, fora desses valores precisaremos fazer ajuste da assimetria da distribuição. 

pd.DataFrame(df_cont.skew(), columns=['Assimetria']).round(2).sort_values(by='Assimetria', ascending=False)

,Assimetria
MiscVal,24.48
LotArea,12.21
3SsnPorch,10.30
LowQualFinSF,9.01
BsmtFinSF2,4.26
ScreenPorch,4.12
EnclosedPorch,3.09
MasVnrArea,2.67
OpenPorchSF,2.36
LotFrontage,2.16


### 2.6) Verificando valores extremos 

In [19]:
# Verificando valores extremos - variáveis contínuas 

import pandas as pd

def verifica_valor_extremo(df, vars_list):
    resultados = []
    total_linhas = len(df)
    
    for var in vars_list:
        df_var = df[var].dropna() # Remove nulos para não distorcer os quartis
        Q1 = df_var.quantile(0.25)
        Q3 = df_var.quantile(0.75)
        IQR = Q3 - Q1
        limite_inferior = Q1 - 1.5 * IQR
        limite_superior = Q3 + 1.5 * IQR
        
        # Conta a quantidade de outliers
        qtd_outliers = ((df_var < limite_inferior) | (df_var > limite_superior)).sum()
        
        # Calcula a porcentagem em relação ao total de linhas do dataset
        pct_outliers = (qtd_outliers / total_linhas) * 100
        
        resultados.append({
            'Variável': var,
            'Qtd_Outliers': qtd_outliers,
            'Percentual_Outliers (%)': round(pct_outliers, 2)
        })
    
    # Converte em DataFrame e ordena pelos maiores percentuais
    df_resultado = pd.DataFrame(resultados)
    return df_resultado.sort_values(by='Percentual_Outliers (%)', ascending=False).reset_index(drop=True)

In [20]:
# Como não há porcentagem maior que 20%, iremos tratar os valores extremos imputando seu valor pela mediana. 

df_outliers = verifica_valor_extremo(df, df_cont.columns)
df_outliers

,Variável,Qtd_Outliers,Percentual_Outliers (%)
0,EnclosedPorch,208,14.25
1,BsmtFinSF2,167,11.44
2,ScreenPorch,116,7.95
3,MasVnrArea,96,6.58
4,LotFrontage,88,6.03
5,OpenPorchSF,77,5.27
6,LotArea,69,4.73
7,SalePrice,61,4.18
8,TotalBsmtSF,61,4.18
9,MiscVal,52,3.56


## 3) Preparação dos dados  

In [21]:
df.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,LotShape,LandContour,Utilities,LotConfig,...,PoolArea,MiscVal,SaleType,SaleCondition,SalePrice,HouseAge,RemodAge,IsRemodeled,IsNewHouse,SeasonSold
0,1,60,RL,65.0,8450,Pave,Reg,Lvl,4,Inside,...,0,0,WD,Normal,208500,5,5,0,0,Winter
1,2,20,RL,80.0,9600,Pave,Reg,Lvl,4,FR2,...,0,0,WD,Normal,181500,31,31,0,0,Spring
2,3,60,RL,68.0,11250,Pave,IR1,Lvl,4,Inside,...,0,0,WD,Normal,223500,7,6,1,0,Autumn
3,4,70,RL,60.0,9550,Pave,IR1,Lvl,4,Corner,...,0,0,WD,Abnorml,140000,91,36,1,0,Winter
4,5,60,RL,84.0,14260,Pave,IR1,Lvl,4,FR2,...,0,0,WD,Normal,250000,8,8,0,0,Winter


In [22]:
# Vamos separar as variáveis de acordo com seu tipo e característica

# 1. Separar o Target e ID  
X = df.drop(columns=['Id', 'SalePrice'], errors='ignore')

# 2. Variáveis Categóricas Ordinais 
var_cat_ord = ['ExterQual', 'ExterCond', 'BsmtQual', 'BsmtCond', 'HeatingQC', 'KitchenQual', 'GarageQual', 'GarageCond', 'BsmtExposure', 'BsmtFinType1', 
                'BsmtFinType2', 'Functional', 'GarageFinish']
var_cat_ord = [col for col in var_cat_ord if col in X.columns] # Garantir que só pegamos as ordinais que realmente existem no dataset

# 3. Variáveis Categóricas Nominais
var_cat_nom = X.select_dtypes(include=['object', 'string']).columns.difference(var_cat_ord).tolist()

# 4. Numéricas (Contínuas e Discretas juntas para imputação/scaling)
LIMITE = 15 
num = X.select_dtypes(include=['int64', 'float64']).nunique()
var_num = num[num>LIMITE].index

# 5. Demais variáveis por serem categóricas representadas com números inteiros, serão usadas diretamente no modelo. 

### 3.1) Pipeline de transformação

In [23]:
import pandas as pd 
import numpy as np
from sklearn.pipeline import make_pipeline
from sklearn.compose import make_column_transformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, PowerTransformer, OneHotEncoder
from class_outlier import OutlierReplacerIQR

pipeline_cont = make_pipeline(SimpleImputer(strategy='median'), OutlierReplacerIQR(), PowerTransformer(method='yeo-johnson', standardize=True))
pipeline_cat_nom = make_pipeline(SimpleImputer(strategy='most_frequent'), OneHotEncoder(drop='if_binary', handle_unknown='ignore', sparse_output=False))

ct = make_column_transformer((pipeline_cont, var_num), (pipeline_cat_nom, var_cat_nom), remainder='passthrough')
preprocessador = make_pipeline(ct, verbose=False)

In [24]:
# Conferindo as transformações
preprocessador.fit(X)

,"steps steps: list of tuplesList of (name of step, estimator) tuples that are to be chained insequential order. To be compatible with the scikit-learn API, all stepsmust define `fit`. All non-last steps must also define `transform`. See:ref:`Combining Estimators <combining_estimators>` for more details.","[('columntransformer', ...)]"
,"transform_input transform_input: list of str, default=NoneThe names of the :term:`metadata` parameters that should be transformed by thepipeline before passing it to the step consuming it.This enables transforming some input arguments to ``fit`` (other than ``X``)to be transformed by the steps of the pipeline up to the step which requiresthem. Requirement is defined via :ref:`metadata routing <metadata_routing>`.For instance, this can be used to pass a validation set through the pipeline.You can only set this if metadata routing is enabled, which youcan enable using ``sklearn.set_config(enable_metadata_routing=True)``... versionadded:: 1.6",None
,"memory memory: str or object with the joblib.Memory interface, default=NoneUsed to cache the fitted transformers of the pipeline. The last stepwill never be cached, even if it is a transformer. By default, nocaching is performed. If a string is given, it is the path to thecaching directory. Enabling caching triggers a clone of the transformersbefore fitting. Therefore, the transformer instance given to thepipeline cannot be inspected directly. Use the attribute ``named_steps``or ``steps`` to inspect estimators within the pipeline. Caching thetransformers is advantageous when fitting is time consuming. See:ref:`sphx_glr_auto_examples_neighbors_plot_caching_nearest_neighbors.py`for an example on how to enable caching.",None
,"verbose verbose: bool, default=FalseIf True, the time elapsed while fitting each step will be printed as itis completed.",False
Name,Type,Value
"feature_names_in_ feature_names_in_: ndarray of shape (`n_features_in_`,)Names of features seen during :term:`fit`. Only defined if theunderlying estimator exposes such an attribute when fit... versionadded:: 1.0","ndarray[object](75,)","['MSSubClass','MSZoning','LotFrontage',...,'IsRemodeled','IsNewHouse', 'SeasonSold']"
n_features_in_ n_features_in_: intNumber of features seen during :term:`fit`. Only defined if theunderlying first estimator in `steps` exposes such an attributewhen fit... versionadded:: 0.24,int,75
,"transformers transformers: list of tuplesList of (name, transformer, columns) tuples specifying thetransformer objects to be applied to subsets of the data.name : str Like in Pipeline and FeatureUnion, this allows the transformer and its parameters to be set using ``set_params`` and searched in grid search.transformer : {'drop', 'passthrough'} or estimator Estimator must support :term:`fit` and :term:`transform`. Special-cased strings 'drop' and 'passthrough' are accepted as well, to indicate to drop the columns or to pass them through untransformed, respectively.columns : str, array-like of str, int, array-like of int, array-like of bool, slice or callable Indexes the data on its second axis. Integers are interpreted as positional columns, while strings can reference DataFrame columns by name. A scalar string or int should be used where ``transformer`` expects X to be a 1d array-like (vector), otherwise a 2d array will be passed to the transformer. A callable is passed the input data `X` and can return any of the above. To select multiple columns by name or dtype, you can use :obj:`make_column_selector`.","[('pipeline-1', ...), ('pipeline-2', ...)]"
,"remainder remainder: {'drop', 'passthrough'} or estimator, default='drop'By default, only the specified columns in `transformers` aretransformed and combined in the output, and the non-specifiedcolumns are dropped. (default of ``'drop'``).By specifying ``remainder='passthrough'``, all remaining columns thatwere not specified in `transformers`, but present in the data passedto `fit` will be automatically passed through. This s

In [25]:
feature_names = preprocessador.get_feature_names_out()
transformed_data_array = preprocessador.transform(X)
transformed_df = pd.DataFrame(transformed_data_array, columns=feature_names)

print(transformed_df.dtypes.value_counts())

transformed_df.head()

float64    211
Name: count, dtype: int64


,pipeline-1__LotFrontage,pipeline-1__LotArea,pipeline-1__MasVnrArea,pipeline-1__BsmtFinSF1,pipeline-1__BsmtFinSF2,pipeline-1__BsmtUnfSF,pipeline-1__TotalBsmtSF,pipeline-1__1stFlrSF,pipeline-1__2ndFlrSF,pipeline-1__LowQualFinSF,...,remainder__TotRmsAbvGrd,remainder__Functional,remainder__Fireplaces,remainder__GarageFinish,remainder__GarageCars,remainder__GarageQual,remainder__GarageCond,remainder__PoolArea,remainder__IsRemodeled,remainder__IsNewHouse
0,-0.271189,-0.278332,1.445138,0.809045,0.0,-0.901984,-0.530092,-0.816858,1.173849,0.0,...,8.0,8.0,0.0,2.0,2.0,3.0,3.0,0.0,0.0,0.0
1,0.810301,0.091500,-0.711575,1.026833,0.0,-0.430943,0.665079,0.462349,-0.869059,0.0,...,6.0,8.0,1.0,2.0,2.0,3.0,3.0,0.0,0.0,0.0
2,-0.054362,0.626729,1.423460,0.579117,0.0,-0.023991,-0.322295,-0.584754,1.176481,0.0,...,6.0,8.0,1.0,2.0,2.0,3.0,3.0,0.0,1.0,0.0
3,-0.633217,0.075363,-0.711575,0.144143,0.0,0.221790,-0.873949,-0.443198,1.150651,0.0,...,7.0,8.0,1.0,1.0,3.0,3.0,3.0,0.0,1.0,0.0
4,1.097659,1.614936,1.501488,0.761247,0.0,0.109198,0.347354,0.134827,1.212873,0.0,...,9.0,8.0,1.0,2.0,3.0,3.0,3.0,0.0,0.0,0.0


## 4) Modelagem 

In [26]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import PowerTransformer

df_variaveis = df.drop(columns=['Id', 'SalePrice'])

x_treino, x_teste, y_treino, y_teste = train_test_split(df_variaveis, df['SalePrice'], test_size=0.20, random_state=5)

target_norm = PowerTransformer(standardize=True)
# Ajusta no treino
y_treino_norm = target_norm.fit_transform(y_treino.values.reshape(-1, 1))
# Apenas transforma o teste (usando o aprendizado do treino)
y_teste_norm = target_norm.transform(y_teste.values.reshape(-1, 1))

### 4.1) Regressão linear múltipla - modelo base 

In [96]:
from sklearn.linear_model import LinearRegression

modelo_base = LinearRegression()
pipeline_final = make_pipeline(preprocessador, modelo_base)

# Etapa de treino 
pipeline_final.fit(x_treino, y_treino_norm) 

,"steps steps: list of tuplesList of (name of step, estimator) tuples that are to be chained insequential order. To be compatible with the scikit-learn API, all stepsmust define `fit`. All non-last steps must also define `transform`. See:ref:`Combining Estimators <combining_estimators>` for more details.","[('pipeline', ...), ('linearregression', ...)]"
,"transform_input transform_input: list of str, default=NoneThe names of the :term:`metadata` parameters that should be transformed by thepipeline before passing it to the step consuming it.This enables transforming some input arguments to ``fit`` (other than ``X``)to be transformed by the steps of the pipeline up to the step which requiresthem. Requirement is defined via :ref:`metadata routing <metadata_routing>`.For instance, this can be used to pass a validation set through the pipeline.You can only set this if metadata routing is enabled, which youcan enable using ``sklearn.set_config(enable_metadata_routing=True)``... versionadded:: 1.6",None
,"memory memory: str or object with the joblib.Memory interface, default=NoneUsed to cache the fitted transformers of the pipeline. The last stepwill never be cached, even if it is a transformer. By default, nocaching is performed. If a string is given, it is the path to thecaching directory. Enabling caching triggers a clone of the transformersbefore fitting. Therefore, the transformer instance given to thepipeline cannot be inspected directly. Use the attribute ``named_steps``or ``steps`` to inspect estimators within the pipeline. Caching thetransformers is advantageous when fitting is time consuming. See:ref:`sphx_glr_auto_examples_neighbors_plot_caching_nearest_neighbors.py`for an example on how to enable caching.",None
,"verbose verbose: bool, default=FalseIf True, the time elapsed while fitting each step will be printed as itis completed.",False
Name,Type,Value
"feature_names_in_ feature_names_in_: ndarray of shape (`n_features_in_`,)Names of features seen during :term:`fit`. Only defined if theunderlying estimator exposes such an attribute when fit... versionadded:: 1.0","ndarray[object](75,)","['MSSubClass','MSZoning','LotFrontage',...,'IsRemodeled','IsNewHouse', 'SeasonSold']"
n_features_in_ n_features_in_: intNumber of features seen during :term:`fit`. Only defined if theunderlying first estimator in `steps` exposes such an attributewhen fit... versionadded:: 0.24,int,75
,"steps steps: list of tuplesList of (name of step, estimator) tuples that are to be chained insequential order. To be compatible with the scikit-learn API, all stepsmust define `fit`. All non-last steps must also define `transform`. See:ref:`Combining Estimators <combining_estimators>` for more details.","[('columntransformer', ...)]"
,"transform_input transform_input: list of str, default=NoneThe names of the :term:`metadata` parameters that should be transformed by thepipeline before passing it to the step consuming it.This enables transforming some input arguments to ``fit`` (other than ``X``)to be transformed by the steps of the pipeline up to the step which requiresthem. Requirement is defined via :ref:`metadata routing <metadata_routing>`.For instance, this can be used to pass a validation set through the pipeline.You can only set this if metadata routing is enabled, which youcan enable using ``sklearn.set_config(enable_metadata_routing=True)``... versionadded:: 1.6",None
,"memory memory: str or object with the joblib.Memory interface, default=NoneUsed to cache the fitted transformers of the pipeline. The last stepwill never be cached, even if it is a transformer. By default, nocaching is performed. If a string is given, it is the path to thecaching directory. Enabling caching triggers a clone of the transformersbefore fitting. Therefore, the transformer instance given to thepipeline cannot be inspected directly. Use the attribute ``named_steps``or ``steps`` to inspect estimators within the pipeline. Caching thetransformers is advantageous when fittin

In [97]:
# Fazendo as previsões e avaliando o modelo 

y_pred_norm = pipeline_final.predict(x_teste) 
y_pred_real = target_norm.inverse_transform(y_pred_norm)

In [98]:
import numpy as np
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error

r2 = r2_score(y_teste, y_pred_real)
mae = mean_absolute_error(y_teste, y_pred_real)
rmse = np.sqrt(mean_squared_error(y_teste, y_pred_real))

print("R² = %.2f %%" % (r2 * 100))
print("MAE = USD %.2f" % mae)
print("RMSE = USD %.2f" % rmse)

R² = 86.97 %
MAE = USD 16621.68
RMSE = USD 29083.48


- O modelo consegue explicar **86,97%** da variação nos preços das casas usando as variáveis do dataset.

- Se uma casa vale US$ 200.000, um erro de US$ 16.000 (MAE) representa uma margem de cerca de **8%**

- O RMSE (US$ 29k) é consideravelmente maior que o MAE (US$ 16k). Isso implica que o modelo está errando mais em algumas poucas casas.

### 4.2) Avaliação completa do modelo base

In [ ]:
# Usaremos o pacote statsmodels para obter um resumo estatístico do modelo. 

import statsmodels.api as sm

x_treino_transf = preprocessador.fit_transform(x_treino)

if hasattr(x_treino_transf, "toarray"):
    x_treino_transf = x_treino_transf.toarray()

y_treino_norm = y_treino_norm.ravel()

# Adiciona a constante (intercepto) no x transformado
x_treino_sm = sm.add_constant(x_treino_transf)

modelo_sm = sm.OLS(y_treino_norm, x_treino_sm).fit()

try:
    nomes_colunas = preprocessador.get_feature_names_out()
    print(modelo_sm.summary(xname=['const'] + list(nomes_colunas)))
except Exception:
    print(modelo_sm.summary())

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.931
Model:                            OLS   Adj. R-squared:                  0.918
Method:                 Least Squares   F-statistic:                     72.94
Date:                Sun, 26 Jul 2026   Prob (F-statistic):               0.00
Time:                        12:33:33   Log-Likelihood:                -100.08
No. Observations:                1168   AIC:                             564.2
Df Residuals:                     986   BIC:                             1486.
Df Model:                         181                                         
Covariance Type:            nonrobust                                         
                                        coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------------------------------------------------------------------
const 

### $R^2 = 0{,}93$ (Coeficiente de Determinação)

* **O que significa:** O modelo consegue explicar **93,1% da variação** da variável alvo ($y$) com base nas variáveis explicativas ($X$). Em termos práticos, indica um ajuste de altíssima precisão aos dados de treino.

### $R^2$ Ajustado $= 0{,}918$ 

* **O que significa:** É o $R^2$ penalizado pela quantidade de variáveis no modelo. O $R^2$ comum sempre sobe se você adicionar qualquer coluna (mesmo que inútil), enquanto o $R^2$ ajustado só sobe se a nova variável trouxer informação relevante.
* **Sua avaliação:** A diferença entre ele e o $R^2$ é pequena. Isso mostra que **a maioria das variáveis no modelo realmente tem valor informativo**.

### Estatística F $= 72{,}94$ e Prob (F-statistic)[valor-p] $= 0{,}00$

* **O que significa:** O Teste F avalia o modelo **como um todo**. Ele testa a hipótese nula de que *todos os coeficientes das suas variáveis são iguais a zero* (ou seja, se o modelo não é melhor do que simplesmente chutar a média).
* **Sua avaliação:** Como o $p$-valor é $0{,}00$ ($< 0{,}05$), rejeita-se a hipótese nula. Isso confirma matematicamente que o conjunto de variáveis **é estatisticamente significativo para prever o preço**.

### Log-Likelihood $= -100{,}08$ (Verossimilhança)

* **O que significa:** Mede o quão provável é ter observado os seus dados reais dado o modelo ajustado. Quanto **mais próximo de zero**, melhor o ajuste.
* **Sua avaliação:** Isoladamente, o valor de $= -100{,}08$ não diz muito. Ele serve como valor base para comparar dois modelos diferentes no mesmo dataset (o modelo com maior Log-Likelihood vence).

### Critérios de Informação - Akaike e Bayesian Information Criterion 

- **AIC $= 564{,}1$**

- **BIC $= 1486{,}0$**

* **O que significam:** Ambos os critérios medem a **qualidade do modelo equilibrando ajuste vs. complexidade**. Eles penalizam modelos que usam variáveis demais para evitar o *overfitting*. Quanto **MENOR** o valor do AIC e do BIC, melhor o modelo.

* **Sua avaliação:** O **BIC (1486)** está bem acima do **AIC (564)**. O BIC aplica uma penalidade muito mais dura à quantidade de variáveis. Uma diferença tão grande sugere que o seu modelo está usando **muitas variáveis/colunas** (provavelmente por causa do One-Hot Encoding).

### Resumo do Diagnóstico

**Diagnóstico:** O modelo é robusto ($R^2 > 93\%$) e estatisticamente válido (Estatística F). Porém, a disparidade entre AIC e BIC indica que ele pode estar **superdimensionado** (muitas variáveis).

### 4.3) Testes de validação de uma regressão 

In [94]:
import numpy as np
import pandas as pd
import scipy.stats as stats
from statsmodels.stats.diagnostic import het_breuschpagan
from statsmodels.stats.outliers_influence import variance_inflation_factor
from statsmodels.stats.stattools import durbin_watson

def avaliar_pressupostos_regressao(
    pipeline, 
    preprocessador, 
    target_transformer, 
    x_teste, 
    y_teste, 
    variaveis_selecionadas=None
):
    """
    Avalia os pressupostos estatísticos de um modelo de regressão linear.
    
    Parâmetros:
    -----------
    pipeline : sklearn.pipeline.Pipeline
        Pipeline do Scikit-Learn treinado.
    preprocessador : ColumnTransformer ou similar
        Objeto responsável pela transformação das features de entrada.
    target_transformer : PowerTransformer ou similar
        Objeto de transformação da variável resposta (com inverse_transform).
    x_teste : pandas.DataFrame ou numpy.ndarray
        Dados de entrada de teste.
    y_teste : pandas.Series ou numpy.ndarray
        Valores reais da variável resposta (escala original).
    variaveis_selecionadas : list, opcional
        Lista com nomes das colunas mantidas pelo modelo (ex: Lasso). 
        Se None, utiliza todas as colunas geradas pelo preprocessador.
        
    Retorna:
    --------
    dict: Dicionário contendo os resultados dos testes e o DataFrame do VIF.
    """
    
    # 1. Transformação dos dados e geração da matriz tratada
    x_teste_transf = preprocessador.transform(x_teste)
    nomes_colunas = preprocessador.get_feature_names_out()
    x_matriz_proc = pd.DataFrame(x_teste_transf, columns=nomes_colunas)

    # 2. Previsões e Cálculo dos Resíduos na escala real
    y_pred_norm = pipeline.predict(x_teste)
    if y_pred_norm.ndim == 1:
        y_pred_norm = y_pred_norm.reshape(-1, 1)
        
    y_pred_real = target_transformer.inverse_transform(y_pred_norm).ravel()
    
    # Garantindo formato de array unidimensional para y_teste
    y_true = y_teste.values if hasattr(y_teste, 'values') else y_teste
    residuos = y_true.ravel() - y_pred_real

    # 3. Filtragem das variáveis (Lasso/Seleção) para os testes de matriz
    if variaveis_selecionadas is not None:
        x_matriz_teste = x_matriz_proc[variaveis_selecionadas]
    else:
        x_matriz_teste = x_matriz_proc

    # --- TESTE 1: NORMALIDADE DOS RESÍDUOS (Shapiro-Wilk) ---
    print("="*50)
    print("1. TESTE DE NORMALIDADE (Shapiro-Wilk)")
    print("="*50)
    
    stat_shapiro, p_shapiro = stats.shapiro(residuos)
    print(f"Estatística de Teste: {stat_shapiro:.4f}")
    print(f"Valor-p: {p_shapiro:.4e}")
    if p_shapiro > 0.05:
        print("RESULTADO: Resíduos possuem distribuição NORMAL (p > 0.05).")
    else:
        print("RESULTADO: Resíduos NÃO seguem distribuição normal (p <= 0.05).")

    # --- TESTE 2: HOMOCEDASTICIDADE (Breusch-Pagan) ---
    print("\n" + "="*50)
    print("2. TESTE DE HOMOCEDASTICIDADE (Breusch-Pagan)")
    print("="*50)
    
    x_com_const = np.column_stack([np.ones(len(x_matriz_teste)), x_matriz_teste.values])
    lm_stat, p_bp, f_stat, f_p = het_breuschpagan(residuos, x_com_const)
    print(f"Estatística de Teste: {lm_stat:.4f}")
    print(f"Valor-p: {p_bp:.4e}")
    if p_bp > 0.05:
        print("RESULTADO: Homocedasticidade mantida (variância dos erros é constante).")
    else:
        print("RESULTADO: Heterocedasticidade detectada (variância dos erros oscila).")

    # --- TESTE 3: AUTOCORRELAÇÃO DOS ERROS (Durbin-Watson) ---
    print("\n" + "="*50)
    print("3. INDEPENDÊNCIA DOS RESÍDUOS (Durbin-Watson)")
    print("="*50)
    
    dw = durbin_watson(residuos)
    print(f"Estatística Durbin-Watson: {dw:.2f}")
    if 1.5 <= dw <= 2.5:
        print("RESULTADO: Os resíduos NÃO possuem autocorrelação significativa (Pressuposto mantido).")
    elif dw < 1.5:
        print("RESULTADO: Autocorrelação POSITIVA detectada nos resíduos.")
    else:
        print("RESULTADO: Autocorrelação NEGATIVA detectada nos resíduos.")

    # --- TESTE 4: MULTICOLINEARIDADE (VIF) ---
    print("\n" + "="*50)
    print("4. MULTICOLINEARIDADE (VIF - Variance Inflation Factor)")
    print("="*50)
    
    colunas_validas = x_matriz_teste.loc[:, x_matriz_teste.std() > 0]
    
    vif_list = []
    for i in range(colunas_validas.shape[1]):
        with np.errstate(divide='ignore', invalid='ignore'):
            vif_val = variance_inflation_factor(colunas_validas.values, i)
        vif_list.append(vif_val)

    vif_data = pd.DataFrame({"Variável": colunas_validas.columns, "VIF": vif_list})
    vif_sorted = vif_data.sort_values(by="VIF", ascending=False).reset_index(drop=True)
    vif_sorted["Status"] = vif_sorted["VIF"].apply(
        lambda x: "Multicolinearidade Alta" if np.isinf(x) or x > 10 else "OK"
    )

    print(vif_sorted.head(10).to_string(index=False))

    # Dicionário de retorno estruturado
    resultados = {
        'shapiro_stat': stat_shapiro,
        'shapiro_pvalue': p_shapiro,
        'breusch_pagan_stat': lm_stat,
        'breusch_pagan_pvalue': p_bp,
        'durbin_watson': dw,
        'vif_dataframe': vif_sorted,
        'residuos': residuos,
        'y_pred_real': y_pred_real
    }
    
    return resultados

In [99]:
resultados = avaliar_pressupostos_regressao(pipeline=pipeline_final,
                                            preprocessador=preprocessador,
                                            target_transformer=target_norm,
                                            x_teste=x_teste,
                                            y_teste=y_teste)

1. TESTE DE NORMALIDADE (Shapiro-Wilk)
Estatística de Teste: 0.7400
Valor-p: 4.2022e-21
RESULTADO: Resíduos NÃO seguem distribuição normal (p <= 0.05).

2. TESTE DE HOMOCEDASTICIDADE (Breusch-Pagan)
Estatística de Teste: 272.6136
Valor-p: 2.7134e-03
RESULTADO: Heterocedasticidade detectada (variância dos erros oscila).

3. INDEPENDÊNCIA DOS RESÍDUOS (Durbin-Watson)
Estatística Durbin-Watson: 2.14
RESULTADO: Os resíduos NÃO possuem autocorrelação significativa (Pressuposto mantido).

4. MULTICOLINEARIDADE (VIF - Variance Inflation Factor)
                    Variável  VIF                  Status
   pipeline-2__BldgType_1Fam  inf Multicolinearidade Alta
 pipeline-2__BldgType_Duplex  inf Multicolinearidade Alta
 pipeline-2__BldgType_2fmCon  inf Multicolinearidade Alta
pipeline-2__Electrical_FuseP  inf Multicolinearidade Alta
pipeline-2__Electrical_FuseA  inf Multicolinearidade Alta
pipeline-2__Electrical_FuseF  inf Multicolinearidade Alta
pipeline-2__Condition2_Feedr  inf Multicolinearida

### 4.4) Ajustes e correções na modelagem

In [100]:
# Filtrando as variáveis mais importantes. 

import pandas as pd

# Recuperar os nomes reais das variáveis do preprocessador
nomes_colunas = ['const'] + list(preprocessador.get_feature_names_out())

tabela_pvalores = pd.DataFrame({'Coeficiente': modelo_sm.params, 'Erro_Padrão': modelo_sm.bse, 'p_valor': modelo_sm.pvalues})
tabela_pvalores.index = nomes_colunas
tabela_pvalores.index.name = 'Variável'

# Filtra apenas variáveis estatisticamente significativas (p < 0.05)
alpha = 0.05
significativas = tabela_pvalores[tabela_pvalores['p_valor'] < alpha].sort_values(by='p_valor')

significativas

,Coeficiente,Erro_Padrão,p_valor
Variável,,,
pipeline-2__MSZoning_'C (all)',-1.163743e+00,1.138945e-01,2.298126e-23
remainder__OverallQual,1.369883e-01,1.379809e-02,3.321959e-22
remainder__OverallCond,1.034397e-01,1.207004e-02,3.949649e-17
pipeline-1__3SsnPorch,1.670899e-13,2.046876e-14,9.903643e-16
const,-1.063756e+00,1.418737e-01,1.442574e-13
...,...,...,...
pipeline-2__RoofStyle_Hip,-2.104919e-01,9.671284e-02,2.975737e-02
pipeline-1__MasVnrArea,-4.095502e-02,1.885590e-02,3.009342e-02
pipeline-2__Heating_Floor,-5.867046e-01,2.752396e-01,3.328532e-02


In [ ]:
# Teremos que aplicar técnicas de seleção de variáveis e regularização na nossa regressão. 

from sklearn.linear_model import LassoCV
from sklearn.pipeline import make_pipeline

lasso = LassoCV(cv=10, random_state=42, n_jobs=-1)
pipeline_final = make_pipeline(preprocessador, lasso)

pipeline_final.fit(x_treino, y_treino_norm.ravel()) 

y_pred_norm = pipeline_final.predict(x_teste) 

y_pred_real = target_norm.inverse_transform(y_pred_norm.reshape(-1, 1))

coefs = pd.Series(lasso.coef_, index=feature_names)
selecionadas_lasso = coefs[coefs != 0].index.tolist()

print("--- LASSO ---")
print(f"Alpha ideal encontrado: {lasso.alpha_:.4f}")
print(f"Variáveis selecionadas ({len(selecionadas_lasso)}): {selecionadas_lasso}")

--- LASSO ---
Alpha ideal encontrado: 0.0037
Variáveis selecionadas (65): ['pipeline-1__LotFrontage', 'pipeline-1__LotArea', 'pipeline-1__MasVnrArea', 'pipeline-1__BsmtFinSF1', 'pipeline-1__BsmtUnfSF', 'pipeline-1__TotalBsmtSF', 'pipeline-1__1stFlrSF', 'pipeline-1__2ndFlrSF', 'pipeline-1__GrLivArea', 'pipeline-1__GarageYrBlt', 'pipeline-1__GarageArea', 'pipeline-1__WoodDeckSF', 'pipeline-1__OpenPorchSF', 'pipeline-1__HouseAge', 'pipeline-1__RemodAge', 'pipeline-2__CentralAir_Y', 'pipeline-2__Condition1_Norm', 'pipeline-2__Exterior1st_BrkFace', 'pipeline-2__Foundation_BrkTil', 'pipeline-2__Foundation_PConc', 'pipeline-2__GarageType_BuiltIn', 'pipeline-2__LandSlope_Gtl', 'pipeline-2__LotConfig_CulDSac', 'pipeline-2__LotConfig_Inside', "pipeline-2__MSZoning_'C (all)'", 'pipeline-2__MSZoning_FV', 'pipeline-2__MSZoning_RM', 'pipeline-2__Neighborhood_BrkSide', 'pipeline-2__Neighborhood_CollgCr', 'pipeline-2__Neighborhood_Crawfor', 'pipeline-2__Neighborhood_Edwards', 'pipeline-2__Neighborhood

In [92]:
import numpy as np
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error

r2 = r2_score(y_teste, y_pred_real)
mae = mean_absolute_error(y_teste, y_pred_real)
rmse = np.sqrt(mean_squared_error(y_teste, y_pred_real))

print("R² = %.2f %%" % (r2 * 100))
print("MAE = USD %.2f" % mae)
print("RMSE = USD %.2f" % rmse)

R² = 83.48 %
MAE = USD 16435.16
RMSE = USD 32743.63


In [119]:
# Chamando a função passando as variáveis do Lasso
resultados = avaliar_pressupostos_regressao(pipeline=pipeline_final,
                                            preprocessador=preprocessador,
                                            target_transformer=target_norm,
                                            x_teste=x_teste,
                                            y_teste=y_teste,
                                            variaveis_selecionadas=selecionadas_lasso)

1. TESTE DE NORMALIDADE (Shapiro-Wilk)
Estatística de Teste: 0.6006
Valor-p: 1.8607e-25
RESULTADO: Resíduos NÃO seguem distribuição normal (p <= 0.05).

2. TESTE DE HOMOCEDASTICIDADE (Breusch-Pagan)
Estatística de Teste: 133.1439
Valor-p: 1.3313e-06
RESULTADO: Heterocedasticidade detectada (variância dos erros oscila).

3. INDEPENDÊNCIA DOS RESÍDUOS (Durbin-Watson)
Estatística Durbin-Watson: 2.08
RESULTADO: Os resíduos NÃO possuem autocorrelação significativa (Pressuposto mantido).

4. MULTICOLINEARIDADE (VIF - Variance Inflation Factor)
                         Variável        VIF                  Status
    pipeline-2__SeasonSold_Summer 376.200250 Multicolinearidade Alta
    pipeline-2__SeasonSold_Spring 215.469088 Multicolinearidade Alta
    pipeline-2__SeasonSold_Autumn 112.236815 Multicolinearidade Alta
    pipeline-2__SeasonSold_Winter  93.658818 Multicolinearidade Alta
 pipeline-2__SaleCondition_Normal  24.344432 Multicolinearidade Alta
             pipeline-1__HouseAge  18.3874

### 4.5) Usando modelos Não-Lineares

Modelos de Árvores de Decisão e Ensemble (como Random Forest, XGBoost ou LightGBM) não possuem pressupostos estatísticos:

- Não exigem normalidade dos resíduos.

- Não sofrem com heterocedasticidade.

- Não são afetados por multicolinearidade (VIF).

- Capturam relações não-lineares e interações entre variáveis que a regressão linear ignora.

In [29]:
import numpy as np
from sklearn.ensemble import HistGradientBoostingRegressor
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error

modelo_nl = HistGradientBoostingRegressor(random_state=42)

pipeline_final = make_pipeline(preprocessador, modelo_nl)

pipeline_final.fit(x_treino, y_treino_norm.ravel()) 


,"steps steps: list of tuplesList of (name of step, estimator) tuples that are to be chained insequential order. To be compatible with the scikit-learn API, all stepsmust define `fit`. All non-last steps must also define `transform`. See:ref:`Combining Estimators <combining_estimators>` for more details.","[('pipeline', ...), ('histgradientboostingregressor', ...)]"
,"transform_input transform_input: list of str, default=NoneThe names of the :term:`metadata` parameters that should be transformed by thepipeline before passing it to the step consuming it.This enables transforming some input arguments to ``fit`` (other than ``X``)to be transformed by the steps of the pipeline up to the step which requiresthem. Requirement is defined via :ref:`metadata routing <metadata_routing>`.For instance, this can be used to pass a validation set through the pipeline.You can only set this if metadata routing is enabled, which youcan enable using ``sklearn.set_config(enable_metadata_routing=True)``... versionadded:: 1.6",None
,"memory memory: str or object with the joblib.Memory interface, default=NoneUsed to cache the fitted transformers of the pipeline. The last stepwill never be cached, even if it is a transformer. By default, nocaching is performed. If a string is given, it is the path to thecaching directory. Enabling caching triggers a clone of the transformersbefore fitting. Therefore, the transformer instance given to thepipeline cannot be inspected directly. Use the attribute ``named_steps``or ``steps`` to inspect estimators within the pipeline. Caching thetransformers is advantageous when fitting is time consuming. See:ref:`sphx_glr_auto_examples_neighbors_plot_caching_nearest_neighbors.py`for an example on how to enable caching.",None
,"verbose verbose: bool, default=FalseIf True, the time elapsed while fitting each step will be printed as itis completed.",False
Name,Type,Value
"feature_names_in_ feature_names_in_: ndarray of shape (`n_features_in_`,)Names of features seen during :term:`fit`. Only defined if theunderlying estimator exposes such an attribute when fit... versionadded:: 1.0","ndarray[object](75,)","['MSSubClass','MSZoning','LotFrontage',...,'IsRemodeled','IsNewHouse', 'SeasonSold']"
n_features_in_ n_features_in_: intNumber of features seen during :term:`fit`. Only defined if theunderlying first estimator in `steps` exposes such an attributewhen fit... versionadded:: 0.24,int,75
,"steps steps: list of tuplesList of (name of step, estimator) tuples that are to be chained insequential order. To be compatible with the scikit-learn API, all stepsmust define `fit`. All non-last steps must also define `transform`. See:ref:`Combining Estimators <combining_estimators>` for more details.","[('columntransformer', ...)]"
,"transform_input transform_input: list of str, default=NoneThe names of the :term:`metadata` parameters that should be transformed by thepipeline before passing it to the step consuming it.This enables transforming some input arguments to ``fit`` (other than ``X``)to be transformed by the steps of the pipeline up to the step which requiresthem. Requirement is defined via :ref:`metadata routing <metadata_routing>`.For instance, this can be used to pass a validation set through the pipeline.You can only set this if metadata routing is enabled, which youcan enable using ``sklearn.set_config(enable_metadata_routing=True)``... versionadded:: 1.6",None
,"memory memory: str or object with the joblib.Memory interface, default=NoneUsed to cache the fitted transformers of the pipeline. The last stepwill never be cached, even if it is a transformer. By default, nocaching is performed. If a string is given, it is the path to thecaching directory. Enabling caching triggers a clone of the transformersbefore fitting. Therefore, the transformer instance given to thepipeline cannot be inspected directly. Use the attribute ``named_steps``or ``steps`` to inspect estimators within the pipeline. Caching thetransformers is advantageou

In [30]:
y_pred_norm = pipeline_final.predict(x_teste) 
y_pred_real = target_norm.inverse_transform(y_pred_norm.reshape(-1, 1))

r2 = r2_score(y_teste, y_pred_real)
mae = mean_absolute_error(y_teste, y_pred_real)
rmse = np.sqrt(mean_squared_error(y_teste, y_pred_real))

print("R² = %.2f %%" % (r2 * 100))
print("MAE = USD %.2f" % mae)
print("RMSE = USD %.2f" % rmse)

R² = 86.35 %
MAE = USD 16837.67
RMSE = USD 29762.05


### 4.5.1) Fazendo eliminação recursiva de variáveis 

In [34]:
import numpy as np
import pandas as pd
from sklearn.ensemble import HistGradientBoostingRegressor
from sklearn.feature_selection import SequentialFeatureSelector
from sklearn.pipeline import make_pipeline
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error

modelo_nl = HistGradientBoostingRegressor(random_state=42)

# Configurando o Seletor Sequencial de Atributos
seletor = SequentialFeatureSelector(
    estimator=modelo_nl,
    n_features_to_select=40,   
    direction='forward',      
    scoring='r2',
    cv=3,
    n_jobs=-1
)

# Pipeline: Preprocessador -> Seletor -> Modelo Final
pipeline_final = make_pipeline(preprocessador, seletor, modelo_nl)

# Treino
pipeline_final.fit(x_treino, y_treino_norm.ravel())

# Previsão e Inversão da transformação
y_pred_norm = pipeline_final.predict(x_teste)
y_pred_real = target_norm.inverse_transform(y_pred_norm.reshape(-1, 1))

# Avaliação
r2 = r2_score(y_teste, y_pred_real)
mae = mean_absolute_error(y_teste, y_pred_real)
rmse = np.sqrt(mean_squared_error(y_teste, y_pred_real))

print("--- DESEMPENHO APÓS SELEÇÃO (SFS) ---")
print("R² = %.2f %%" % (r2 * 100))
print("MAE = USD %.2f" % mae)
print("RMSE = USD %.2f" % rmse)

--- DESEMPENHO APÓS SELEÇÃO (SFS) ---
R² = 85.97 %
MAE = USD 17555.96
RMSE = USD 30175.60


In [41]:
mascara = pipeline_final.named_steps['sequentialfeatureselector'].get_support()
print(f"Número de variáveis selecionadas: {mascara.sum()} de {len(mascara)}")
colunas_processadas = preprocessador.get_feature_names_out()
colunas_selecionadas = colunas_processadas[mascara]
print("40 Colunas Selecionadas:", colunas_selecionadas)

Número de variáveis selecionadas: 40 de 211
40 Colunas Selecionadas: ['pipeline-1__LotArea' 'pipeline-1__BsmtFinSF1' 'pipeline-1__BsmtFinSF2'
 'pipeline-1__TotalBsmtSF' 'pipeline-1__LowQualFinSF'
 'pipeline-1__GrLivArea' 'pipeline-1__GarageYrBlt'
 'pipeline-1__EnclosedPorch' 'pipeline-1__3SsnPorch'
 'pipeline-1__ScreenPorch' 'pipeline-1__MiscVal' 'pipeline-1__HouseAge'
 'pipeline-2__BldgType_2fmCon' 'pipeline-2__CentralAir_Y'
 'pipeline-2__Condition1_PosA' 'pipeline-2__Condition1_PosN'
 'pipeline-2__Condition1_RRAe' 'pipeline-2__Condition1_RRAn'
 'pipeline-2__Condition1_RRNe' 'pipeline-2__Condition1_RRNn'
 'pipeline-2__Condition2_Artery' 'pipeline-2__Condition2_Feedr'
 'pipeline-2__Condition2_Norm' 'pipeline-2__Condition2_PosA'
 'pipeline-2__Condition2_PosN' 'pipeline-2__Condition2_RRAe'
 'pipeline-2__Condition2_RRAn' 'pipeline-2__Condition2_RRNn'
 'pipeline-2__Electrical_FuseF' 'pipeline-2__Electrical_FuseP'
 "pipeline-2__Exterior2nd_'Wd Sdng'" 'pipeline-2__HouseStyle_SFoyer'
 'pipeli

### 4.6) Usando somente as melhores variáveis para predição 

Isso vai poupar muito processamento e aumentar a eficiência. 

In [27]:
colunas_selecionadas = [
    'pipeline-1__LotArea',
    'pipeline-1__BsmtFinSF1',
    'pipeline-1__BsmtFinSF2',
    'pipeline-1__TotalBsmtSF',
    'pipeline-1__LowQualFinSF',
    'pipeline-1__GrLivArea',
    'pipeline-1__GarageYrBlt',
    'pipeline-1__EnclosedPorch',
    'pipeline-1__3SsnPorch',
    'pipeline-1__ScreenPorch',
    'pipeline-1__MiscVal',
    'pipeline-1__HouseAge',
    'pipeline-2__BldgType_2fmCon',
    'pipeline-2__CentralAir_Y',
    'pipeline-2__Condition1_PosA',
    'pipeline-2__Condition1_PosN',
    'pipeline-2__Condition1_RRAe',
    'pipeline-2__Condition1_RRAn',
    'pipeline-2__Condition1_RRNe',
    'pipeline-2__Condition1_RRNn',
    'pipeline-2__Condition2_Artery',
    'pipeline-2__Condition2_Feedr',
    'pipeline-2__Condition2_Norm',
    'pipeline-2__Condition2_PosA',
    'pipeline-2__Condition2_PosN',
    'pipeline-2__Condition2_RRAe',
    'pipeline-2__Condition2_RRAn',
    'pipeline-2__Condition2_RRNn',
    'pipeline-2__Electrical_FuseF',
    'pipeline-2__Electrical_FuseP',
    "pipeline-2__Exterior2nd_'Wd Sdng'",
    'pipeline-2__HouseStyle_SFoyer',
    'pipeline-2__LandContour_Low',
    'pipeline-2__MSZoning_RM',
    'pipeline-2__Neighborhood_Crawfor',
    'pipeline-2__Neighborhood_Edwards',
    'remainder__MSSubClass',
    'remainder__OverallQual',
    'remainder__OverallCond',
    'remainder__GarageCars'
]

In [40]:
import numpy as np
from sklearn.pipeline import make_pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import FunctionTransformer
from sklearn.ensemble import HistGradientBoostingRegressor


modelo_nl = HistGradientBoostingRegressor(random_state=42)

# Certifique-se de DESATIVAR a saída Pandas no preprocessador 
preprocessador.set_output(transform="default")

# Pega a lista exata de nomes que o preprocessador gera
todas_colunas = list(preprocessador.get_feature_names_out())

# Encontra a posição NUMÉRICA de cada uma das 40 colunas selecionadas
indices_40 = []
for col in colunas_selecionadas:
    if col in todas_colunas:
        indices_40.append(todas_colunas.index(col))
    else:
        print(f"Atenção: A coluna '{col}' não foi encontrada no preprocessador!")

print(f"Total de índices encontrados com sucesso: {len(indices_40)}/40")

# Função limpa para cortar a matriz NumPy pelo índice
def filtrar_por_posicao(X):
    return X[:, indices_40]

seletor_posicao = FunctionTransformer(filtrar_por_posicao)

# Pipeline Final
pipeline_producao = make_pipeline(preprocessador, seletor_posicao, modelo_nl)

# Treina o pipeline
pipeline_producao.fit(x_treino, y_treino_norm.ravel())

# Validação final
print("--------------------------------------------------")
print("Número de features recebidas pelo modelo:", pipeline_producao[-1].n_features_in_)

Total de índices encontrados com sucesso: 40/40
--------------------------------------------------
Número de features recebidas pelo modelo: 40


In [41]:
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error

# Previsão e Inversão da transformação
y_pred_norm = pipeline_producao.predict(x_teste)
y_pred_real = target_norm.inverse_transform(y_pred_norm.reshape(-1, 1))

# Avaliação
r2 = r2_score(y_teste, y_pred_real)
mae = mean_absolute_error(y_teste, y_pred_real)
rmse = np.sqrt(mean_squared_error(y_teste, y_pred_real))

print("--- DESEMPENHO APÓS SELEÇÃO (SFS) ---")
print("R² = %.2f %%" % (r2 * 100))
print("MAE = USD %.2f" % mae)
print("RMSE = USD %.2f" % rmse)

--- DESEMPENHO APÓS SELEÇÃO (SFS) ---
R² = 85.97 %
MAE = USD 17555.96
RMSE = USD 30175.60


## Análise Comparativa e Conclusão

| Cenário | Qtd. Variáveis | Redução de Variáveis | $R^2$ (%) | MAE (USD) | RMSE (USD) |
| :--- | :---: | :---: | :---: | :---: | :---: |
| **Modelo Completo** | 211 | — | **86,35%** | **$ 16.837,67** | **$ 29.762,05** |
| **Modelo Selecionado (SFS)** | 40 | **-81%** | **85,97%** | **$ 17.555,96** | **$ 30.175,60** |
| *Diferença Absoluta* | *-171* | — | *-0,38%* | *+$ 718,29* | *+$ 413,55* |

### 1. A Vantagem de Reduzir 81% das Variáveis

O resultado do processo de seleção de variáveis (*Sequential Feature Selector*) apresenta uma troca extremamente vantajosa entre **desempenho preditivo** e **eficiência operacional**.

* **Queda Irrelevante no Desempenho:** A redução da capacidade explicativa do modelo ($R^2$) foi de apenas **0,38%** (de 86,35% para 85,97%). Em termos práticos de negócio, o erro médio (MAE) subiu cerca de **$ 718**, uma variação muito baixa para o mercado imobiliário.
* **Ganhos Massivos de Performance e Engenharia (Produção):**
* **Latência e Processamento:** Eliminar 171 variáveis significa uma redução de **81% na carga de dados**. O pré-processamento, a imputação de nulos e o *one-hot encoding* ficam infinitamente mais rápidos.
* **Manutenção e Qualidade dos Dados:** Em um ambiente de produção, manter e monitorar *pipelines* para 211 colunas gera alto custo de governança. Reduzir para 40 variáveis diminui drasticamente o risco de erros por *drift* de dados, falta de preenchimento ou quebra de dependências.
* **Interpretabilidade:** Um modelo com 40 atributos permite que stakeholders e analistas entendam claramente quais fatores (área construída, qualidade geral, localização, etc.) realmente impactam o valor do imóvel.

**Princípio da Parcimônia (Navalha de Ockham):** O modelo simplificado é muito mais robusto, fácil de implantar e menos suscetível a *overfitting*, justificando com sobra a leve variação nas métricas.


### 2. Avaliação das Métricas Finais no Contexto do Dataset Ames Housing

Considerando o contexto do **Ames Housing Dataset** (preços de imóveis na cidade de Ames, Iowa):

1. **Poder Explicativo ($R^2 \approx 86\%$):**
Um $R^2$ de **85,97%** demonstra que o modelo consegue capturar a grande maioria da variabilidade dos preços das casas usando apenas as variáveis mais relevantes. 
2. **Erro Médio Absoluto ($\text{MAE} \approx \$ 17,555$):**
No dataset de Ames, a mediana do valor de venda das casas gira em torno de **$ 160.000**.
* Um MAE de ~$17,5k representa um **erro percentual médio relativo próximo de 10% a 11%** em relação ao valor do imóvel.
* Para previsões imobiliárias automatizadas (AVM - *Automated Valuation Models*), uma margem de erro médio nessa faixa é considerada bastante competitiva e funcional para triagem e estimativa inicial de mercado.

3. **Análise do RMSE ($\text{RMSE} \approx \$ 30,175$):**
O RMSE é sensível a *outliers* (imóveis de altíssimo luxo com preços muito atípicos). Como o RMSE (~$30k) é consideravelmente maior que o MAE (~$17,5k), isso indica que o dataset contém algumas casas de alto valor cujos preços o modelo erra por uma margem maior, penalizando o RMSE.

### 3. Impacto Prático do Modelo no Negócio Imobiliário

A aplicação deste modelo preditivo simplificado (40 variáveis) vai além dos ganhos técnicos, gerando impacto direto na operação de **imobiliárias, fintechs de crédito imobiliário e investidores**. 

#### A. Aceleração da Precificação e Redução do CAC (Custo de Aquisição de Cliente)
No modelo tradicional, precificar um imóvel exige a coleta manual de centenas de informações e a vistoria presencial de corretores.
* **Com 211 variáveis:** O formulário de captação de imóveis seria exaustivo para o proprietário, gerando alta taxa de abandono no site/app.
* **Com 40 variáveis:** O cliente preenche apenas os dados essenciais (área construída, qualidade do acabamento, quantidade de garagens, bairro), permitindo uma **avaliação instantânea (AVM)**. Isso reduz o tempo de onboarding de dias para **segundos**, aumentando a conversão de leads.

#### B. Exemplo Prático: Aderência do Erro Médio (MAE) à Margem de Negociação
A mediana de valor das casas no mercado de Ames é de aproximadamente **US$ 160.000**, e o erro médio absoluto (MAE) do nosso modelo ficou em **US$ 17.555** (~10,9% do valor médio).

>**Exemplo de Cenário Real:**

> Imagine uma casa cujo valor real de mercado seja **US$ 160.000**.
> * **Estimativa do Modelo:** US$ 142.500 a US$ 177.500.
> * **Aplicação Prática:** No mercado imobiliário, a margem habitual de negociação/desconto entre o preço anunciado e a venda final gira entre **8% e 12%**. 
> * **Resultado para o Negócio:** A margem de erro do modelo coincide exatamente com a margem natural de barganha humana. O modelo não precisa acertar o valor exato no centavo, mas sim colocar o imóvel na **faixa de preço correta** para evitar que ele fique encalhado por sobrepreço ou venda por valor abaixo do mercado.

#### C. Proteção Financeira e Mitigação de Riscos de Crédito
Para instituições bancárias que usam o imóvel como garantia (hipoteca/alienação fiduciária):
* O modelo atinge um **$R^2$ de ~86%**, o que garante alta confiança ao determinar o *LTV (Loan-to-Value)* — a proporção do empréstimo em relação ao valor do imóvel.
* Saber que 86% da variação de preço é explicada objetivamente por esses 40 fatores protege a carteira de crédito contra avaliações superfaturadas ou fraudulentas.

#### D. Otimização de Reformas e Investimentos (*Fix & Flip*)
Como o modelo foca nas 40 variáveis mais relevantes, investidores conseguem simular o **Retorno sobre o Investimento (ROI)** de uma reforma antes de gastar dinheiro.

> * **Exemplo:** O modelo permite simular quanto o valor final da casa aumenta ao reformar o porão (`TotalBsmtSF`) versus adicionar uma vaga de garagem (`GarageCars`). O investidor foca o orçamento estritamente nas variáveis que o algoritmo provou que adicionam valor real ao imóvel.

### Conclusão Final

O modelo com **40 variáveis** é claramente a melhor escolha para implementação final/produção. Ele entrega praticamente a **mesma precisão** que o modelo com 211 colunas, porém com **muito mais estabilidade, menor tempo de execução e manutenção simplificada**.